### ISSUE TITLE
Week 05 - Day 2 - JavaScript Iteration

### ISSUE THREAD

**Issue by gstark** [JFlynn426/assignments#16]
# JavaScript Iteration

## Objectives

After completing this assignment, you should be able to:

* Demonstrate an understanding of iteration/enumeration

## Instructions

1. Fork [this repository](https://github.com/suncoast-devs/js-iteration) to your own account.
2. Change into your projects directory:
3. Clone your repository: `git clone js-iteration`
4. Change into your project's directory: `cd js-iteration`
5. Install the dependencies: `yarn install` (or just `yarn` for short)
6. Open in your editor]
7. Start the test runner: `yarn test`
7. Open `src/functions.test.js` and work on functions until tests pass.
8. Commit and push your work to GitHub.
9. Turn in the URL to your GitHub repo.

## Explorer Mode

- All tests passing
- No linter warnings
- Turn in the homework using the URL to your repository on GitHub.

## Additional Resources

Reference the documentation on DevDocs to find what kind of helpful functions might already be in JavaScript.

- [String Functions on DevDocs](https://devdocs.io/javascript/global_objects/string).
- [Array Functions on DevDocs](http://devdocs.io/javascript/global_objects/array).

**Comment by JFlynn426** [comment]
https://github.com/JFlynn426/js-iteration-master

**Comment by gstark** [comment]
Good work!

**Comment by gstark** [comment]
Your homework was marked: **Exceeds Expectations**

![Shake it cus you made it!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBIUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f8192466340c451ea46a1b17477b92f5f01a8ba7/danding%20pup.gif)
> &ldquo;Shake it cus you made it!&rdquo;
__&mdash; via **[Katherine Trammell](https://gifs.suncoast.io/venerations/19)**__
