### ISSUE TITLE
Week 06 - Day 2 - One List

### ISSUE THREAD

**Issue by gstark** [JFlynn426/assignments#19]
In this assignment, you'll build a classic todo manager.

Something like: [One List](https://one-list.ambetha.surge.sh)

## Objectives

- Reinforce component architecture in React
- Effective use props and state in React

## Requirements

We're going to build todo manager. The user should be able to:
- Add new todo items
- Mark todo items as complete
- Delete todo items

Read the [documentation](https://one-list-api.herokuapp.com)

### Explorer Mode

- [ ] Allow a todo to be created
- [ ] Mark a todo complete
- [ ] Delete a todo item

### Adventure Mode

- [ ] Allow the text of a todo item to be changed

### Epic Mode

- [ ] Allow for multiple lists by allowing the user to specify the `access token`

**Comment by JFlynn426** [comment]
https://github.com/JFlynn426/one-list

**Comment by gstark** [comment]
Your homework was marked: **Exceeds Expectations**

![You got it!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBHUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d2c38988a8a66323675b11efd93094c28cccadde/cat%20rainbow.gif)
> &ldquo;You got it!&rdquo;
__&mdash; via **[Katherine Trammell](https://gifs.suncoast.io/venerations/15)**__
