### ISSUE TITLE
Week 01 - Day 2 - Expanding Your World

### ISSUE THREAD

**Issue by gstark** [JFlynn426/assignments#2]
In this assignment you will end up with a simple styled web page, published on the web.

## Objectives

- Practice using your tools text editor
- Explore new CSS properties
- Publish a web page

## Requirements

- Have `git`, `hub`, and `node` installed. We should have done this together in class.

### Explorer Mode

- [ ] Follow all of the setup instructions (See "Assignment Setup").
- [ ] Using CSS, style your page to imitate some of the classic designs of the web. Feel free to make this look as "bad" as you want. Here are some sites to gain inspiration:
  - [10 90s websites designs you won’t believe existed](https://www.justinmind.com/blog/10-90s-websites-designs-you-wont-believe-existed/)
- [ ] Add a second page about your hobby with (at least) 2 pictures and with other facts about your hobby.
- [ ] Add a menu to the your site so a user can go back and forth between the new pages.
- [ ] Between the 2 pages, use at least 5 tag selectors, 5 id selectors, and 5 class selectors to style content on your page.
- [ ] Deploy your site.

### Adventure Mode

- [ ] use pseudo-classes to style elements when you hover the mouse over them
- [ ] Add a third page, that has a table. Create this table to have alternating colored rows, and a hover over color.
- [ ] Make a nav bar that sticks to the top of the page (see the nav bar here for example: https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes)
- [ ] Make a footer that always sticks to the bottom of the page

### Epic Mode

- [ ] Explore CSS animations and add some life to your static page. Feel free to really dig into these and try to animated all elements on your page to some extent

### CSS

- [Introduction to CSS](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS)
- [Getting Started with CSS Rules](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics#Anatomy_of_a_CSS_ruleset)
- [All the CSS properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference#Keyword_index)
- [pseudo-classes and pseudo-elements](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Pseudo-classes_and_pseudo-elements)

### HTML

- [HTML Tags](https://developer.mozilla.org/en-US/Learn/HTML/HTML_tags)
- [Evolution of the Web](http://www.evolutionoftheweb.com)

## Reading Material

To prep for tomorrow's lesson, you can [read about flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/).

**Comment by JFlynn426** [comment]
Explorer mode done. (publishing in a few seconds)

**Comment by JFlynn426** [comment]
https://github.com/JFlynn426/hello-world

**Comment by gstark** [comment]
Your homework was marked: **Meets Expectations**

![Gavin Approved!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cd97f19100495726ff64a3d09a685c898b2e76b3/gavin-lol.gif)
> &ldquo;Gavin Approved!&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/1)**__
