### ISSUE TITLE
Week 07 - Day 1 - React Practice

### ISSUE THREAD

**Issue by gstark** [JFlynn426/assignments#22]
In this assignment, you will practice your React skills

## Objectives

* Use components and props effectively in React
* Use React Router to create declarative navigation in your application

### Explorer Mode

- *READ* each of the following assignments and choose one that you feel will help you practice the most:
 - Add React Router to your `Choose your own API` homework
 - Redo `Cloudy With a Chance of Syntax Error` in React
 - Redo `Blackjack` in React
 - Redo `Roshambo` in React
 - Do [Pet Adoption](https://suncoast.io/handbook/curriculum/front-end/react-ii/assignments/pet-adoption/)
 - Do [Crypto Ticker](https://suncoast.io/handbook/curriculum/front-end/react-i/assignments/crypto-ticker) with React and React Router (to show the details of one currency)
 - Do [Party Like It's 1989](https://suncoast.io/handbook/curriculum/front-end/react-i/assignments/party-like-its-1989)
 - Implement a different `Choose your own API`

### Adventure Mode

- Choose another of the above and create a second app

**Comment by JFlynn426** [comment]
https://github.com/JFlynn426/blackjack-react

**Comment by gstark** [comment]
Your homework was marked: **Meets Expectations**

![Gavin Approved!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cd97f19100495726ff64a3d09a685c898b2e76b3/gavin-lol.gif)
> &ldquo;Gavin Approved!&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/1)**__
