### ISSUE TITLE
Week 07 - Day 3 - Spit and Polish

### ISSUE THREAD

**Issue by gstark** [JFlynn426/assignments#23]
Your GitHub repository will be part of your portfolio and you will likely link to it from your portfolio.

Creating a clean looking README is as important for a project as having nice clean code.

Here are some examples of great READMEs:
- [https://github.com/axios/axios](https://github.com/axios/axios)
- [https://github.com/Microsoft/vscode](https://github.com/Microsoft/vscode)
- [https://github.com/twbs/bootstrap](https://github.com/twbs/bootstrap)
- [https://github.com/electron/electron](https://github.com/electron/electron)

Here are some example of great student READMEs:
- [https://github.com/cfsanderson/Minesweeper](https://github.com/cfsanderson/Minesweeper)
- [https://github.com/m1g/tic-react-toe](https://github.com/m1g/tic-react-toe)
- [https://github.com/m1g/snowman](https://github.com/m1g/snowman)

## Objectives

- Create quality READMEs (README.md)

### Explorer Mode

- [ ] Choose several (at least three) repositories to update the README.md
- [ ] Include a description, in your own words, of what the assignment was
- [ ] Include a list of technologies (and links to the homepage for each) you used
- [ ] Include a link to the project in production (surge, etc.) - You can edit this by clicking "Edit" in the upper right corner of your repository's home page.
- [ ] Include a screenshot or an animated gif (see https://github.com/wulkano/kap or http://recordit.co/ or https://www.cockos.com/licecap/)
- Optional:
  - [ ] Include an aspect you are particularly proud of
  - [ ] Include a snippet of code you are proud of (see GitHub Markdown on how to format code snippets)

**Comment by JFlynn426** [comment]
https://github.com/JFlynn426/octodex-clone/blob/master/README.md

**Comment by JFlynn426** [comment]
https://github.com/JFlynn426/minesweeper
https://github.com/JFlynn426/blackjack-react
https://github.com/JFlynn426/roshambo/
https://github.com/JFlynn426/photo-gallery

**Comment by gstark** [comment]
Great! Consider adding some screenshots or animated gifs.

**Comment by gstark** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBVdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5aaf4fb8aebc193771c4dd6c9823d8f6300ba70b/giphy-7.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/72)**__
