### ISSUE TITLE
Week 01 - Day 3 - Flexbox

### ISSUE THREAD

**Issue by gstark** [JFlynn426/assignments#3]
Now that we have learned the power of flexbox we will apply it to the sites we are building. We'll also go back to a past assignment and see how flexbox would simplify our HTML and CSS.

## Objectives

- Build on your knowledge of HTML & CSS
- Use flexbox techniques layout pages.
- Implement, from scratch, a given design
- Understand HTML/CSS Layout
- Be able to place elements on a page where you want them.

## Requirements

- You should strive to implement the design as close as possible, though, especially if you've never touch HTML or CSS before, this can be extraordinarily difficult, and will take a lot of practice and mileage.

- **Note**: You should complete at least the tasks given for _explorer_ mode as listed below before turning in the assignment, as well as before attempting _adventure_ or _epic_ modes.

### Explorer Mode

- [ ] Revisit your `exploring your world` assignment and redo your CSS using flexbox where appropriate.
- [ ] Recreate the page 'The Daily Kitteh' using flexbox as closely as you possibly can. Use the same fonts, sizes, and colors. Download some of your favorite
  - ![image](./assets/daily-kitteh.png)

## Adventure Mode

- [ ] Recreate the page `Flebox Article Layout' as closely as possible.
  - ![image](./assets/flexbox-article-layout.png)

## Epic Mode

- [ ] Recreate the page `Skeleton Layout example` as closely as possible.
  - ![image](./assets/skeleton-layout-example.png)

## Additional Resources

- https://css-tricks.com/snippets/css/a-guide-to-flexbox/
- http://www.evolutionoftheweb.com

## Recommended Practice:

- https://flexboxfroggy.com/
- https://mastery.games/p/flexbox-zombies

**Comment by JFlynn426** [comment]
https://github.com/JFlynn426/website-clones

**Comment by JFlynn426** [comment]
https://github.com/JFlynn426/website-clones

**Comment by JFlynn426** [comment]
https://github.com/JFlynn426/hello-world

**Comment by gstark** [comment]
This is great, but your `lastp` paragraph shrinks off screen since your `img` is a fixed size so it doesn't scale as the screen becomes smaller.

**Comment by gstark** [comment]
Your homework was marked: **Meets Expectations**

![Get up and dance!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBSdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3323b129c4533d8a45339c345692fab77f9771ac/meets-1.gif)
> &ldquo;Get up and dance!&rdquo;
__&mdash; via **[Mark Dewey](https://gifs.suncoast.io/venerations/61)**__
